services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: travail_collaboratif
      POSTGRES_PASSWORD: travail_collaboratif
      POSTGRES_DB: travail_collaboratif
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
